# Generated by Django 5.2.5 on 2025-09-05 23:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_production_quantity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, help_text='제품 1개 생산에 필요한 원자재 수량 (kg, L 등 원자재 단위 기준)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='단위당 소요량')),
                ('unit', models.CharField(help_text='원자재의 단위 (kg, L, 개 등)', max_length=20, verbose_name='단위')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bom_items', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='core.finishedproduct', verbose_name='완제품')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_usages', to='core.rawmaterial', verbose_name='원자재')),
            ],
            options={
                'verbose_name': 'BOM (자재명세서)',
                'verbose_name_plural': 'BOM (자재명세서)',
                'db_table': 'bom',
                'indexes': [models.Index(fields=['finished_product'], name='bom_finishe_9ec217_idx'), models.Index(fields=['raw_material'], name='bom_raw_mat_17febe_idx')],
                'unique_together': {('finished_product', 'raw_material')},
            },
        ),
    ]
